name: End to End tests

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  create_generic_musl_asset:
    name: Create Generic MUSL asset
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add WASM target
      run: rustup target add wasm32-wasi
    - name: Install musl-tools
      run: sudo apt-get install -y --no-install-recommends musl-tools
    - name: Add musl target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Install cargo-make
      run: cargo install --debug cargo-make
    - name: Build asset
      run: cargo make build-e2e
    - uses: actions/upload-artifact@v2
      with:
        name: zellij
        path: target/x86_64-unknown-linux-musl/debug/zellij
  tests_container:
    needs: create_generic_musl_asset
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/linuxserver/openssh-server
      ports:
        - 2222
    steps:
      - name: create asset dir
        run: mkdir -p /usr/src/zellij
      - uses: actions/download-artifact@v2
        with:
          name: zellij
      - name: stay online
        run: tail -f /dev/null
  build:
    needs: create_generic_musl_asset
    name: Run tests on container
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add WASM target
      run: rustup target add wasm32-wasi
    - name: Install cargo-make
      run: test -x "${HOME}/.cargo/bin/cargo-make" || cargo install --debug cargo-make
    - name: Test
      run: cargo test -j 1 -- --ignored
