name: End to End tests

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  tests_container:
    container: ghcr.io/linuxserver/openssh-server
      ports:
        - 2222
      volumes:
        - ./target/x86_64-unknown-linux-musl/debug:/usr/src/zellij
    steps:
      - name: stay online
        run: tail -f /dev/null
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Add WASM target
      run: rustup target add wasm32-wasi
    - name: Install cargo-make
      run: test -x "${HOME}/.cargo/bin/cargo-make" || cargo install --debug cargo-make
    - name: Test
      run: cargo make e2e-test
