name: End to End tests

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Bulild generic binary and run tests on it
    runs-on: ubuntu-latest

    services:
      ssh:
        image: ghcr.io/linuxserver/openssh-server
        env:
          PUID: 1000
          PGID: 1000
          TZ: Europe/Vienna
          PASSWORD_ACCESS: true
          USER_PASSWORD: test
          USER_NAME: test
        ports:
          - 2222:2222
        options: -v ${{ github.workspace }}/target:/usr/src/zellij --name ssh
    steps:
    - uses: actions/checkout@v2
    - name: Add WASM target
      run: rustup target add wasm32-wasi
    - name: Install musl-tools
      run: sudo apt-get install -y --no-install-recommends musl-tools
    - name: Add musl target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Install cargo-make
      run: cargo install --debug cargo-make
    - name: Build asset
      run: cargo make build-e2e
    - name: Restart ssh container
      uses: docker://docker
      with:
        args: docker restart ssh
    - name: Test
      run: cargo make e2e-test
        # run: cargo test -j 1 -- --ignored --nocapture
